### ISSUE TITLE
Search bar not handling accented characters properly

### ISSUE THREAD

**Issue by aitorres** [MarginaliaSearch/encyclopedia.marginalia.nu#1]
Hi, thank you for this interesting experiment! :-) 

I wanted to report a bug with the search bar: if you try to search any term with an accented character (e.g. é), the application will render an 500 internal server error.

You can reproduce by typing this and clicking Search:

<img width="575" alt="Screenshot 2023-08-30 at 10 39 14 PM" src="https://github.com/MarginaliaSearch/encyclopedia.marginalia.nu/assets/26191851/e8cc4e94-47bb-483a-a9dd-3a1c16d8f64c">

I see that, by doing this, the app is directed to the path `https://encyclopedia.marginalia.nu/find/%E9` (note the escaped character).

<img width="471" alt="Screenshot 2023-08-30 at 10 40 33 PM" src="https://github.com/MarginaliaSearch/encyclopedia.marginalia.nu/assets/26191851/9cdfea1a-453a-4c4d-8188-6e3c9e45e3a1">

If I manually set the path to `/find/é`, the search works as expected and results are displayed properly:

<img width="1222" alt="Screenshot 2023-08-30 at 10 41 00 PM" src="https://github.com/MarginaliaSearch/encyclopedia.marginalia.nu/assets/26191851/8b279691-98ad-4b7f-b6b6-4375b3bfe6b2">

I could try finding and solving the issue but it'd take me a few days as I'd need to ramp up on Java / Spark, which I haven't used much before (unless it's a very quick change, but I'm not sure!).

And again, thanks for this project!

**Comment by vlofgren** [comment]
Interesting.  Bug was due to a redirect not doing URL-encoding properly.  Fixed now.
