### ISSUE TITLE
Cannot navigate to any page with a slash in the title

### ISSUE THREAD

**Issue by suddjian** [MarginaliaSearch/encyclopedia.marginalia.nu#3]
The slash gets put in the URL and routes to a directory. For example: https://encyclopedia.marginalia.nu/article/HTTP/3. Should probably map forward slash to an underscore.

**Comment by vlofgren** [comment]
Interesting.  Doesn't seem to work if you urlencode the slash either.

**Comment by vlofgren** [comment]
Fixed and deployed to prod.   You may need to use urlencoded slashes, but the server will accept them:  e.g. https://encyclopedia.marginalia.nu/article/HTTP%2F3

Commit: https://github.com/MarginaliaSearch/encyclopedia.marginalia.nu/commit/efcba2554475466bc5ba7c91c0d02b897f04c701
